name: open_auth_ui
description: Open source, composable, configurable authentication UI kit that works with any provider of your choice.
version: 0.0.1
repository: https://github.com/lohanidamodar/open_auth_ui

environment:
  sdk: ^3.0.2


dependencies:
  flutter_svg: ^2.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
